
public class 메소드_추천 {
	static String recommand() {
		String[] title={
        		"That That (Prod. & Feat. SUGA of BTS)",
        		"봄여름가을겨울 (Still Life)",
        		"TOMBOY",
        		"LOVE DIVE",
        		"사랑인가 봐",
        		"Feel My Rhythm",
        		"사랑은 늘 도망가",
        		"GANADARA (Feat. 아이유)",
        		"LOVE me",
        		"취중고백",
        		"우리들의 블루스",
        		"ZOOM",
        		"다정히 내 이름을 부르면",
        		"다시 만날 수 있을까",
        		"나의 X에게",
        		"신호등",
        		"Celeb",
        		"듣고 싶을까",
        		"이제 나만 믿어요",
        		"INVU",
        		"ELEVEN",
        		"Stay",
        		"무지개",
        		"strawberry moon",
        		"MY BAG",
        		"라일락",
        		"아버지",
        		"A bientot",
        		"감동이야 (Feat. 성시경)",
        		"Celebrity",
        		"너의 모든 순간",
        		"손이 참 곱던 그대",
        		"19금 abcdefu",
        		"회전목마 (Feat. Zion.T & 원슈타인) (Prod. by Slom)",
        		"사랑해 진짜",
        		"사랑역",
        		"Stronger (What Doesn't Kill You)",
        		"연애편지",
        		"FEARLESS",
        		"보금자리",
        		"정이라고 하자 (Feat. 10CM)",
        		"Next Level",
        		"너를 생각해",
        		"리무진 (Feat. MINO) (Prod. by GRAY)",
        		"언제나 사랑해",
        		"사랑해요 그대를",
        		"인생찬가",
        		"Bad Habits",
        		"Weekend",
        		"Butter",
        		"스물다섯, 스물하나",
        		"OHAYO MY NIGHT",
        		"바라만 본다",
        		"Dynamite",
        		"Counting Stars (Feat. Beenzino)",
        		"호랑수월가",
        		"내 손을 잡아",
        		"어제처럼",
        		"흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야",
        		"Seoul",
        		"문득",
        		"초록을거머쥔우리는",
        		"Tiny Riot",
        		"SMILEY (Feat. BIBI)",
        		"That's Hilarious",
        		"2002",
        		"Timeless",
        		"찰나가 영원이 될 때 (The Eternal Moment)",
        		"서랍",
        		"My Universe",
        		"모든 날, 모든 순간 (Every day, Every Moment)",
        		"Permission to Dance",
        		"고백",
        		"RUN2U",
        		"오래된 노래",
        		"밤하늘의 별을 (2020)",
        		"낙하 (With 아이유)",
        		"내가 아니라도",
        		"Blueming",
        		"드라마",
        		"오늘도 빛나는 너에게 (To You My Light) (Feat.이라온)",
        		"Loving You Girl (Feat. Hkeem)",
        		"나는 트로트가 싫어요",
        		"With you",
        		"밤이 깊었네 (Feat. 헤이즈)",
        		"헤픈 우연",
        		"눈이 오잖아 (Feat. 헤이즈)",
        		"Dun Dun Dance",
        		"Step Back",
        		"At My Worst",
        		"작은 것들을 위한 시 (Boy With Luv) (Feat. Halsey)",
        		"만남은 쉽고 이별은 어려워 (Feat. Leellamarz) (Prod. by TOIL)",
        		"Because Of You",
        		"Savage",
        		"Off My Face",
        		"봄 to 러브",
        		"이제는 (Feat. 화사)",
        		"선물",
        		"사이렌 Remix (Feat. UNEDUCATED KID & Paul Blanco)",
        		"롤린 (Rollin')",
        		"Every Second",
        		"존재만으로",
        		"에잇 (Prod. & Feat. SUGA of BTS)",
        		"아무래도 난",
        		"12 : 45 (Stripped)",
        		"여행",
        		"Hey Mama (Feat. Nicki Minaj & Bebe Rexha & Afrojack)",
        		"겨울잠",
        		"19금 Peaches (Feat. Daniel Caesar & Giveon)",
        		"Real Love",
        		"밝게 빛나는 별이 되어 비춰줄게",
        		"어떻게 이별까지 사랑하겠어, 널 사랑하는 거지",
        		"아로하",
        		"너의 번호를 누르고 (Prod. by 영화처럼)",
        		"비와 당신",
        		"초대",
        		"그게 더 편할 것 같아 (N번째 연애 X 멜로망스)",
        		"추억은 만남보다 이별에 남아",
        		"Savage Love (Laxed - Siren Beat) (BTS Remix)",
        		"내 곁에",
        		"봄날",
        		"Bad",
        		"사랑하게 될 줄 알았어",
        		"Starlight",
        		"우리가 헤어져야 했던 이유",
        		"Dance Monkey",
        		"Memories",
        		"Dreams Come True",
        		"주저하는 연인들을 위해",
        		"나보다 더 사랑해요",
        		"parachute",
        		"만개 (Prod. 신지후)",
        		"METEOR",
        		"어땠을까 (Feat. 박정현)",
        		"그래서 그래 (Feat. 윤하)",
        		"취기를 빌려 (취향저격 그녀 X 산들)",
        		"Way Back Home",
        		"흰눈",
        		"여름가을겨울 봄.",
        		"비가 오는 날엔 (2021)",
        		"너, 너 (N번째 연애 X 휘인 (Whee In))",
        		"잊을 수 있을까",
        		"운전만해 (We Ride)",
        		"Shape Of You",
        		"첫눈처럼 너에게 가겠다",
        		"어떻게 지내 (Prod. by VAN.C)",
        		"우연히 봄",
        		"늦은 밤 너의 집 앞 골목길에서",
        		"Wake Up (Prod. by 코드 쿤스트)",
        		"Kiss Me More (Feat. SZA)",
        		"Lovesick Girls",
        		"밤편지",
        		"그날에 나는 맘이 편했을까",
        		"Light Switch",
        		"마음을 드려요",
        		"마지막 너의 인사",
        		"Rainy day (Feat. ASH ISLAND & Skinny Brown)",
        		"시간을 거슬러 (낮에 뜨는 달 X 케이윌)",
        		"너의 번호를 누르고",
        		"쉬어 (Feat. MINO) (Prod. by GRAY)",
        		"안녕",
        		"GANJI (Feat. Jessi)",
        		"Can't Control Myself",
        		"Ashes",
        		"어푸 (Ah puh)",
        		"시작",
        		"희재",
        		"멜로디",
        		"Good Boy Gone Bad",
        		"레이디버드",
        		"슬픔이여안녕",
        		"사랑인가 봐 (Acoustic Ver.)",
        		"벚꽃이 피면 우리 그만 헤어져",
        		"Paris In The Rain",
        		"좋아좋아",
        		"있잖아",
        		"기억해 줘요",
        		"LOVE",
        		"잠이 오질 않네요",
        		"고맙소",
        		"Christmas Tree",
        		"사실 나는 (Feat. 전건호)",
        		"MILLIONS",
        		"9INTRO",
        		"노래 (The Song)",
        		"살았소",
        		"다시 사랑한다면 (김필 Ver.)",
        		"Don't Start Now",
        		"네가 없는 밤 (Feat. ASH ISLAND) (Prod. by GRAY)",
        		"Whisky on the Rock",
        		"DAYDREAM",
        		"All For You",
        		"우산이 없어요",
        		"살짝 설렜어 (Nonstop)",
        		"상상더하기",
        		"Leave The Door Open",
        		"Forever Young",
        		"선물 (Feat. 은지원)",
        		"하루만 더",
        		"Circles"
        };
		String result="";
		int no = (int)(Math.random()*title.length);
		result=title[no];
		return result;
	}
	public static void main(String[] args) {
		String title = recommand();
		System.out.println(title);

	}

}
